### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by Lawouach** [jg-rp/python-jsonpath#59]
Hi,

Just wanted to thank you for this awesome json path library. The best I've tried and the most pleasing to work with.

Keep up the good work!

**Comment by jg-rp** [comment]
Hi @Lawouach,

You are welcome, and thank you for the words of encouragement.

**Comment by Lawouach** [comment]
It's not much but I feel open source these days is too much in trouble for projects like yours to not get praise they deserve!
